name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - run: touch dist/.nojekyll
      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist
      - uses: actions/deploy-pages@v3
